version: "3.9"

services:
  postgres:
    image: postgres
    container_name: whip-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: whipuser
      POSTGRES_PASSWORD: whipuser_password
      POSTGRES_DB: whip_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
